// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// dfcop_pdf_cpp
Eigen::VectorXd dfcop_pdf_cpp(const Eigen::VectorXd& w, const Eigen::MatrixXd& pv, const Eigen::MatrixXd& x);
RcppExport SEXP _mdmd_dfcop_pdf_cpp(SEXP wSEXP, SEXP pvSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type pv(pvSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(dfcop_pdf_cpp(w, pv, x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mdmd_dfcop_pdf_cpp", (DL_FUNC) &_mdmd_dfcop_pdf_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_mdmd(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
