# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dfcop_pdf_cpp <- function(w, pv, x) {
    .Call('mdmd_dfcop_pdf_cpp', PACKAGE = 'mdmd', w, pv, x)
}

